### ISSUE TITLE
student_index_spec.rb

### ISSUE THREAD

**Issue by Ms-Alex** [learn-co-curriculum/rails-restful-index-action-lab#10]
describe 'Multiple students are shown' do
  it 'on the index page' do
    Student.create!(first_name: "Daenerys", last_name: "Targaryen")
    Student.create!(first_name: "Lindsey", last_name: "Stirling")

    visit "/students"

    expect(page).to have_content(/(?=.*Daenerys)(?=.*Lindsey).*/)
  end
end

I--------------I
I believe that the line: 
'expect(page).to have_content(/(?=.*Daenerys)(?=.*Lindsey).*/)' 
should maybe be: 
'expect(page).to have_content(/(?=.*Daenerys)(?=.*Targaryen).*/) .

That was the only way I was able to pass the test. Unless I'm wrong. Then I have no idea what I did..

-Alex

**Comment by maxcell** [comment]
I'm going to close this issue since this was a duplicate from #11. Once again, thank you 🎉!
