### ISSUE TITLE
Instructions Do Not Match or Pass RSPEC

### ISSUE THREAD

**Issue by yunglleung1** [learn-co-curriculum/rails-restful-index-action-lab#13]
**Current Instruction:** Map an **index.html.erb** view file to the student controller and iterate over the list of students returned from the index action in the controller

**Correction: students.html.erb**

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials including the Readme and believe your issue to have been resolved. By convention, the view should be `index.html.erb` as mentioned in the Readme, but the file should be placed within a `students` folder within `views`. This is necessary for the Students controller to automatically locate the appropriate view

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
