### ISSUE TITLE
Confusing instructions.

### ISSUE THREAD

**Issue by wendisha** [learn-co-curriculum/rails-restful-index-action-lab#14]
Instructions call for placing the index.html.erb file within a view/students folder, but Capybara tests expect it to be placed in a student folder (singular).

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
