### ISSUE TITLE
Lab order

### ISSUE THREAD

**Issue by rohanphillips** [learn-co-curriculum/rails-restful-index-action-lab#17]
It feels like this lab should come after https://learn.co/tracks/full-stack-web-development-v7/rails/intro-to-rest/rails-dynamic-request , in the current learning order we're asked to create a dynamic routes before a lab example is done.

**Comment by drakeltheryuujin** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
