### ISSUE TITLE
Student Version 404 & learn error

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/rails-restful-index-action-lab#2]
<img width="415" alt="screen shot 2016-01-05 at 2 32 54 pm" src="https://cloud.githubusercontent.com/assets/14326883/12116317/45507f8c-b3b9-11e5-96e6-e73424dad9cf.png">

Despite the message above, no fork was made (that I can see).

At the time of writing the 'View on Github' gives 404:
https://github.com/learn-co-students/rails-restful-index-action-lab-v-000

'Raise an issue' links here, to the curriculum version.

Lab being referenced:
https://learn.co/tracks/full-stack-web-development/rails/intro-to-rest/restful-action-index-lab

**Comment by AnnJohn** [comment]
Hi @onyoo sorry about that again. We looked into it this morning, and it's been fixed. Thanks for raising the issue!
