### ISSUE TITLE
assert_text error

### ISSUE THREAD

**Issue by musiccity365** [learn-co-curriculum/rails-restful-index-action-lab#27]
tests used to have `assert_text('Daenerys', 'Lindsey')`

but I was getting this error:

```
Failures:

  1) Multiple students are shown on the index page
     Failure/Error: assert_text('Daenerys', 'Lindsey')
     
     ArgumentError:
       Daenerys is not a valid type for a text query
```

until we made this change:

`assert_text('Daenerys Targaryen')
    assert_text('Lindsey Stirling')`

**Comment by bagrad007** [comment]
if someone struggles with this, I had the same issue, and after replacing the new assert_text in the spec/features directory on the student_index_spec.rb, I had to split this assert_text('Daenerys Targaryen') assert_text('Lindsey Stirling'), onto two separate lines, like so: 

assert_text('Daenerys Targaryen') 
assert_text('Lindsey Stirling')

I was able to pass after making that change!

**Comment by lizbur10** [comment]
Hi there! Thank you for spotting this issue and submitting feedback. The spec file has been updated to correct the problem so I am closing this issue.

Thanks for contributing to the Flatiron School curriculum! 💙
