### ISSUE TITLE
Possible resource link

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/rails-restful-index-action-lab#3]
I think it would save future students some time wondering how to build resourceful routes if they had this link: 

http://edgeguides.rubyonrails.org/routing.html

It's a great read. Just a thought :)

**Comment by AnnJohn** [comment]
thanks @onyoo We'll add this as a Resource in the lesson. 

Also, Avi told us of the issues with viewing lessons. We're fixing all of the deployed ones right and they should be good to go. The ones that you specifically said you had issues with can be viewed now. Thanks again for raising all these issues, and we're also improving our lesson deployment tool so this should not be an issue very soon.

**Comment by onyoo** [comment]
@AnnJohn Thanks so much. I know you guys are working hard, and I really appreciate it!

**Comment by AnnJohn** [comment]
Awesome, and thank you! Also just added your resource. Thanks for sending it along again!
