### ISSUE TITLE
Viewing the index page raises an error

### ISSUE THREAD

**Issue by Dom-Mc** [learn-co-curriculum/rails-restful-index-action-lab#5]
When attempting to view the index page It's showing  `undefined method '+' for nil:NilClass`.  Looks like the db comes with a record that contains several attributes set to nil.

For #to_s (Student class), instead of `self.first_name + " " + self.last_name`, changing it to 
`"#{self.first_name} #{self.last_name}"` prevents the error.

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by mendelB** [comment]
Thanks @Dom-Mc! this was fixed with #6

**Comment by mendelB** [comment]
Thanks @Dom-Mc! this was fixed with #6
